version: "3.9"

services:
  mongodb:
    container_name: mongodb_service
    image: "mongo:latest"
    ports:
      - "27017:27017"

  redis:
    container_name: redis_service
    image: "redis:latest"
    ports:
      - "6379:6379"

  app:
    container_name: wops
    build:
      context: .
    ports:
      - "3000:3000"
    depends_on:
      - mongodb
      - redis
    environment:
      - PORT=3000
      - MONGO_HOST=mongodb
      - MONGO_PORT=27017
      - REDIS_HOST=redis
      - REDIS_PORT=6379
